### PR TITLE
Bug fixes (#121, #122)

### LINKED ISSUE #121: Quit event not sent to client on play from another login
When player explicitly quits (using the "quit" command), the 'quit' event is sent to the client.
 
But that 'quit' event is not sent to the client when player connects from another login session with the same character. The first session is kicked out and returns to the authenticated state, but the client is not informed of this change.

This has no impact on the regular client (except that the "playing" observable remains "true", but this is not used otherwise), but this is probably unfortunate for bots (I'm planning one) or more graphical clients (I am currently developing one), which can't track state change (playing => logged) to react accordingly.

### LINKED ISSUE #122: Broken command parsing due to method change
Commit f16fd30eb40d37affa6e28217bcad7c053eaa852 made findMatch a static method, but this apparently broke things.

Only basic commands work now (e.g. directions), all those implying arguments and henceforth findNearby() or findInside() fails on error.

E.g.
```
eval someObject.findInside('someName')
```
Results in:
```
TypeError: WorldObjectClassBuilder.findMatch is not a function
    at Proxy.findInside (/home/..../src/lib/world-object-class-builder.js:341:40)
...
```

### PR DESCRIPTION
**Pull request by Omikhleia**
**Changes:**

Fix #121: Send 'quit' event also on forced quit due to login from another session
- Just added an 'emit' message in that case, as done when player quits

Fix #122 Wrong class method
- WorldObjectClassBuilder.findMatch => WorldObject.findMatch
- Removed findMatch from documentation (no longer exposed in-world)

### CODE REVIEW

**Comment by doughsay** [comment]
Sorry I didn't see this until now.  Thanks for your contributions!  I'll take a look soon and see about getting these merged.

**Comment by doughsay** [comment]
Thanks for contributing!

You mentioned in your bug reports that you're working on a bot and a more graphical client.  I'm very curious how that's coming along.  Would you mind sharing?  We could add it to the readme of this repo if you think it's generally useful.

**Comment by Omikhleia** [comment]
Hi Chris,

Regarding your questions --

As for the graphical client, I have to say it's still very experimental,
and probably not much interesting yet, but it's here nevertheless --
https://github.com/Omikhleia/room.js-ng2-cli

It's king of an exercise learning and practicing Angular, but it's probably
not very usable as it is.

On the game engine side, it basically relies on a few JSON payloads to be
sent to the client, in order to play sounds -- one-shot effects and
ambiant/cycling sounds in a room --, display players and their roles (i.e.
developer or not) in the left pane (somehow inspired by Slack, even in the
color scheme...), and updating room exits and contents, as well as player
inventory.

There's kind of an isometric map view (very rough for now) and players can
move via clicking on the exits in the isometric map.

I plan to have some activation-by-click and drag and drop features on
items, but I am not happy with these features as first experimented, so I
haven't pushed them yet to the repository ; unfortunately I've been rather
busy at work these past months, without time to progress and find something
satisfying.

And I'm afraid that's basically all at this stage ;-)
I am including a few screenshot below, so that you can get a feeling about
it without having to try to install it ^^
(Well, verb and function editing is supported too, as it was an important
feature in your own client.)

As for the bot, I haven't pushed anything yet - it's just a basic node
program that connects as a player, but beyond that raw building block, it
doesn't do anything very clever so far.

Regards.

2017-05-21 21:04 GMT+02:00 Chris Dosé <notifications@github.com>:

**Comment by doughsay** [comment]
That's very cool!  Thanks for sharing.  I've been busy myself, but have decided to get back into it a bit.  The bot sounds interesting because I'd like to try and build a good black-box style testing framework for the server.  Basically the idea would be to programmatically connect to a server and perform tasks and verify that they worked. This could help increase confidence that things are working as expected, and help when doing large refactors.

**Pull request merged**
